### ISSUE TITLE
Serials service layer

### ISSUE THREAD

**Issue by egorvlgavr** [malygina/mySerials#11]
This task must be done before #9 !
Create Exceptions in separate package **org.myserials.exceptions** all exceptions must be runtime.
**SerialNotFoundException** (SNFE) with id and message

Create service layer for serals with following methods:
**String id create(Serial)** -> save serial and return autogenerated id
**List&lt;Serial&gt;getAll(limit)** -> return limited number of serials sorted by its rating. if there is no serials just empty list.
**Serial getById(id)** -> return specific serial if not found throw SNFE
**void update(Serial)** -> update serial **id must stay same it is very important for future REST layer** if serial with such id not exist throw SNFE
**void delete(id)** -> delete by id if not found throw SNFE

Please, create unit tests on happy path and bad path using [mocked](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html#boot-features-testing-spring-boot-applications-mocking-beans) repository from DAO layer.

**Comment by egorvlgavr** [comment]
[Video](https://www.youtube.com/watch?v=nwM7A4TwU3M) about  "street magic" of Spring Data

**Comment by malygina** [comment]
1. I have some misunderstanding about create method. Why I should return only id parameter? Why not all object?

**Comment by malygina** [comment]
[Query creation. Spring Data JPA](http://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.query-methods.query-creation)
