### ISSUE TITLE
REST error handling and dto validation

### ISSUE THREAD

**Issue by egorvlgavr** [malygina/mySerials#14]
Create controller that will handle errors and create proper responses use 4 apprach (Controller advice) from this [paper](http://www.baeldung.com/exception-handling-for-rest-with-spring#controlleradvice)
Use spring annotation **Valid** to validate DTO objects and also create proper error validation response.
here is useful [link](https://www.petrikainulainen.net/programming/spring-framework/spring-from-the-trenches-adding-validation-to-a-rest-api/) as for original error use same controller advice.

**Comment by malygina** [comment]
[Conversion](http://www.baeldung.com/entity-to-and-from-dto-for-a-java-spring-application) entity to dto

**Comment by malygina** [comment]
error handling was merged
