### ISSUE TITLE
DAO Catalog Layer

### ISSUE THREAD

**Issue by malygina** [malygina/mySerials#3]
Create DAO Catalog Layer. Use Spring Data JPA (Hibernate). https://spring.io/guides/gs/accessing-data-jpa/

**Comment by egorvlgavr** [comment]
Please, let's use [flyway](https://flywaydb.org/) for database intializing. It's greate tool and it is supported in spring-boot-data-jpa out of the box! here is it [description](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html#howto-execute-flyway-database-migrations-on-startup)
Like in sample let's use hibernate for scheme validation.

**Comment by malygina** [comment]
@egorvlgavr 
What kind of methods should I declare in repository interface?

**Comment by egorvlgavr** [comment]
@malygina let's use origin crud repository. More complex methods will be on Service layer.

**Comment by malygina** [comment]
What approach we will use for writing flyway migrations: sql or java ?
