### ISSUE TITLE
REST api Catalog layer

### ISSUE THREAD

**Issue by egorvlgavr** [malygina/mySerials#9]
Create simple CRUD rest service for serials catalog based on [Spring MVC](https://spring.io/guides/gs/rest-service/)
Here is small description of [REST contracts](http://www.restapitutorial.com/lessons/httpmethods.html)
Lets use **/serials** for entire collection and **/serials/{id}** for specific element
Please implement:
1. POST **/serials** for adding new serial (id must be autogenerated and mentioned in  'Location' header)
2. GET  **/serials** for entire collection (no pagination just fixed size 10 sort by rating)
3. GET **/serials/{id}** for specific serial
4. PUT **/serials/{id}** update serial
5. DELETE **/serials/{id}** delete serial

**Comment by malygina** [comment]
@egorvlgavr I used default pagination for get serials
